// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiYoj4yXfMvvb1apm93dtE3G3aR_2wx9g',
    appId: '1:934196658036:web:56153f10df68cc28a33621',
    messagingSenderId: '934196658036',
    projectId: 'whatsapp-49574',
    authDomain: 'whatsapp-49574.firebaseapp.com',
    storageBucket: 'whatsapp-49574.appspot.com',
    measurementId: 'G-WQBZE4QD23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_4nlbP3U_TqFPWGdHN8jLfgcau3nxLzo',
    appId: '1:934196658036:android:c0e392fd9a34fe49a33621',
    messagingSenderId: '934196658036',
    projectId: 'whatsapp-49574',
    storageBucket: 'whatsapp-49574.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5aaF8zqpnYfTmO5XMx_6Tr9ptCiw3P3A',
    appId: '1:934196658036:ios:3cc1176b687604c4a33621',
    messagingSenderId: '934196658036',
    projectId: 'whatsapp-49574',
    storageBucket: 'whatsapp-49574.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5aaF8zqpnYfTmO5XMx_6Tr9ptCiw3P3A',
    appId: '1:934196658036:ios:3cc1176b687604c4a33621',
    messagingSenderId: '934196658036',
    projectId: 'whatsapp-49574',
    storageBucket: 'whatsapp-49574.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
