// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsgdogmXQLprjQpjHtZPo9ue__a6o9Lvg',
    appId: '1:710820747943:web:d0230dd86e6b66562e5982',
    messagingSenderId: '710820747943',
    projectId: 'uber-1bf28',
    authDomain: 'uber-1bf28.firebaseapp.com',
    storageBucket: 'uber-1bf28.appspot.com',
    measurementId: 'G-C5XE0Z17BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2DNXb_5dimHmYQOZcateVBh91C0VwwzE',
    appId: '1:710820747943:android:72bfa20c6cbe30682e5982',
    messagingSenderId: '710820747943',
    projectId: 'uber-1bf28',
    storageBucket: 'uber-1bf28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7oR2RyW9xC66KVwOr7zIYzefdAhOTBWc',
    appId: '1:710820747943:ios:8293af08a8ee0b3f2e5982',
    messagingSenderId: '710820747943',
    projectId: 'uber-1bf28',
    storageBucket: 'uber-1bf28.appspot.com',
    iosBundleId: 'com.example.uber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7oR2RyW9xC66KVwOr7zIYzefdAhOTBWc',
    appId: '1:710820747943:ios:8293af08a8ee0b3f2e5982',
    messagingSenderId: '710820747943',
    projectId: 'uber-1bf28',
    storageBucket: 'uber-1bf28.appspot.com',
    iosBundleId: 'com.example.uber',
  );
}
