// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1JUk8EbpqQQghJI0_BGEoBH34pwv1H_E',
    appId: '1:613474338148:web:59a142a6d847f1d3eea671',
    messagingSenderId: '613474338148',
    projectId: 'minhasviagens-973d8',
    authDomain: 'minhasviagens-973d8.firebaseapp.com',
    storageBucket: 'minhasviagens-973d8.appspot.com',
    measurementId: 'G-K82X0C1N7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO1gT_H2pMjWjLFpuVBvSBGhb37cS6WXM',
    appId: '1:613474338148:android:316e010ef5a07f6deea671',
    messagingSenderId: '613474338148',
    projectId: 'minhasviagens-973d8',
    storageBucket: 'minhasviagens-973d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNPNEBErAwchPLaY7RGJifq0y77uNTeO4',
    appId: '1:613474338148:ios:bcbe23a06597818eeea671',
    messagingSenderId: '613474338148',
    projectId: 'minhasviagens-973d8',
    storageBucket: 'minhasviagens-973d8.appspot.com',
    iosBundleId: 'com.example.geolocalizacao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNPNEBErAwchPLaY7RGJifq0y77uNTeO4',
    appId: '1:613474338148:ios:bcbe23a06597818eeea671',
    messagingSenderId: '613474338148',
    projectId: 'minhasviagens-973d8',
    storageBucket: 'minhasviagens-973d8.appspot.com',
    iosBundleId: 'com.example.geolocalizacao',
  );
}
