// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa3YwX-7rYGBn0E-EAswqaVmLsANr8jcE',
    appId: '1:636063315221:web:62fc335c85c7b766eae51c',
    messagingSenderId: '636063315221',
    projectId: 'appolx-7ba98',
    authDomain: 'appolx-7ba98.firebaseapp.com',
    storageBucket: 'appolx-7ba98.appspot.com',
    measurementId: 'G-ZV9XH2P3QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKWqqo-B2FdOxZSGPF8qmSctVz2EPfu1Q',
    appId: '1:636063315221:android:d0ff17949afbea63eae51c',
    messagingSenderId: '636063315221',
    projectId: 'appolx-7ba98',
    storageBucket: 'appolx-7ba98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5NdQLp0hDqOI0njtQBZx_edCpe6OPATY',
    appId: '1:636063315221:ios:c7c3af69b724319beae51c',
    messagingSenderId: '636063315221',
    projectId: 'appolx-7ba98',
    storageBucket: 'appolx-7ba98.appspot.com',
    iosBundleId: 'com.example.olx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5NdQLp0hDqOI0njtQBZx_edCpe6OPATY',
    appId: '1:636063315221:ios:c7c3af69b724319beae51c',
    messagingSenderId: '636063315221',
    projectId: 'appolx-7ba98',
    storageBucket: 'appolx-7ba98.appspot.com',
    iosBundleId: 'com.example.olx',
  );
}
